# Generated by Django 4.1.2 on 2023-01-05 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kreasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('gambar', models.FileField(null=True, upload_to='testi/')),
                ('komentar', models.CharField(max_length=100)),
                ('status_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pencerita_app.status')),
            ],
        ),
        migrations.CreateModel(
            name='Karya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penulis', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('koordinat', models.CharField(max_length=100)),
                ('kota', models.CharField(max_length=100)),
                ('judul', models.CharField(max_length=100)),
                ('karangan', models.TextField()),
                ('kreasi_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pencerita_app.kreasi')),
            ],
        ),
    ]
